server:
  port : 8088



spring:
  application:
    name: config-server
  profile :
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moAllElite/gestion-employee-microservice
        default-label: main